name: Build

on: [push]

steps:
  - uses: actions/checkout@master

  - uses: actions/setup-go@v1
    with:
      go-version: '1.14.0'

  - name: Build image
    run: docker build .

  - name: Run tests
    run: go test .
