name: Pipeline

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: '1.14'

      - name: Restore cache
        uses: actions/cache@preview
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}

      - name: Check for missing license header
        run: ./scripts/check_licenses.sh

      - name: Build image
        run: docker build .

      - name: Run tests
        run: go test .

      - name: Lint
        uses: actions-contrib/golangci-lint@v1
