name: Pipeline

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      IMAGE_MANIFEST_TAG: batect/batect-cache-init-image:${{ github.sha }}
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Setup Golang
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.14'

      - name: Setup golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sudo sh -s -- -b /usr/local/bin v1.23.8

      - name: Restore cache
        uses: actions/cache@preview
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}

      - name: Check for missing license header
        run: ./scripts/check_licenses.sh

      - name: Lint
        run: golangci-lint run .

      - name: Run tests
        run: ./scripts/test.sh

      - name: Log in to Docker Hub
        if: github.repository == 'batect/batect-cache-init-image' && github.ref == 'refs/heads/main'
        run: docker login -u $USERNAME -p $PASSWORD
        env:
          USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push images and manifest
        if: github.repository == 'batect/batect-cache-init-image' && github.ref == 'refs/heads/main'
        run: ./scripts/build_and_push.sh ${{ env.IMAGE_MANIFEST_TAG }}

      - name: Update image reference in main Batect repo
        if: github.repository == 'batect/batect-cache-init-image' && github.ref == 'refs/heads/main'
        run: ./scripts/update_batect_image_ref.sh
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_PUSH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_PUSH_TOKEN }}
          COMMIT_SHA: ${{ github.sha }}
