name: Pipeline

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: batect/batect-cache-init-image:${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: '1.14'

      - name: Setup golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sudo sh -s -- -b /usr/local/bin v1.23.8

      - name: Restore cache
        uses: actions/cache@preview
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}

      - name: Check for missing license header
        run: ./scripts/check_licenses.sh

      - name: Lint
        run: golangci-lint run .

      - name: Build application
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o docker/app .

      - name: Build image
        run: docker build -t $IMAGE_TAG docker
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}

      - name: Run tests
        run: go test .
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}

      - name: Log in to Docker Hub
        if: github.repository == 'batect/batect-cache-init-image' && github.ref == 'refs/heads/main'
        run: docker login -u $USERNAME -p $PASSWORD
        env:
          USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push image
        if: github.repository == 'batect/batect-cache-init-image' && github.ref == 'refs/heads/main'
        run: docker push $IMAGE_TAG
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}

      - name: Update image reference in main batect repo
        if: github.repository == 'batect/batect-cache-init-image' && github.ref == 'refs/heads/main'
        run: ./scripts/update_batect_image_ref.sh
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_PUSH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_PUSH_TOKEN }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          COMMIT_SHA: ${{ github.sha }}
